# Generated by Django 4.0 on 2021-12-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_book_user_remove_manga_user_delete_anime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('unfinished', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('watchlist', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('dropped', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('unfinished', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('watchlist', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('dropped', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('unfinished', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('watchlist', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('dropped', models.JSONField(default={'item_ids': ['hello', 'world']})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
