# Generated by Django 4.0 on 2022-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='dropped',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='finished',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='unfinished',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='watchlist',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='book',
            name='dropped',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='book',
            name='finished',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='book',
            name='unfinished',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='book',
            name='watchlist',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='manga',
            name='dropped',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='manga',
            name='finished',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='manga',
            name='unfinished',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='manga',
            name='watchlist',
            field=models.JSONField(default=[]),
        ),
    ]
