# Generated by Django 4.0 on 2021-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='dropped',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='anime',
            name='finished',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='anime',
            name='unfinished',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='anime',
            name='watchlist',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='book',
            name='dropped',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='book',
            name='finished',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='book',
            name='unfinished',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='book',
            name='watchlist',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='manga',
            name='dropped',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='manga',
            name='finished',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='manga',
            name='unfinished',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
        migrations.AlterField(
            model_name='manga',
            name='watchlist',
            field=models.TextField(default={'item_ids': ['hello', 'world']}),
        ),
    ]
